### ISSUE TITLE
How to install older version?

### ISSUE THREAD

**Issue by jmasaki24** [espressif/binutils-esp32ulp#14]
I can't find any older releases of the toolchain. the MSYS2 homepage has a 2019-05-24 version. Is there any way I could get older versions?
```
WARNING: Toolchain version is not supported: esp32-2019r1
Expected to see version: crosstool-ng-1.22.0-80-g6c4433a
Please check ESP-IDF setup instructions and update the toolchain, or proceed at your own risk.
WARNING: Compiler version is not supported: 8.2.0
Expected to see version(s): 5.2.0
Please check ESP-IDF setup instructions and update the toolchain, or proceed at your own risk.
```

**Comment by igrr** [comment]
You can find the URL on the documentation page for the IDF version you have. Here is the link for the latest stable version. You can switch between versions using the pop-up menu on the bottom left of the page. https://docs.espressif.com/projects/esp-idf/en/stable/get-started/windows-setup-scratch.html#alternative-setup-just-download-a-toolchain

**Comment by jmasaki24** [comment]
Thank you! The stable version is what I was looking for.
