### ISSUE TITLE
no 'bin' folder exists within binutils

### ISSUE THREAD

**Issue by pushtoopen** [espressif/binutils-esp32ulp#15]
The legacy gnu make instructions for esp32 binutils [https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/ulp-legacy.html](https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/ulp-legacy.html) states that the repository should be downloaded and the 'bin' folder should be added to the PATH variable. But regardless of binutils release, the 'bin' folder does not exist, and no other clarification is available.

**Comment by pushtoopen** [comment]
Run the following:
git clone https://github.com/espressif/binutils-esp32ulp.git
cd binutils-esp32ulp
./configure --target=esp32ulp-elf --prefix=$PWD/esp32ulp-elf-binutils
make
make install-strip

**Comment by igrr** [comment]
Alternatively, you may download the binary version from the releases page.
