### ISSUE TITLE
Incorectly translated 'JUMP Rx` instruction.

### ISSUE THREAD

**Issue by Mucka** [espressif/binutils-esp32ulp#2]
I had little problem with using unconditional jumps to the address from the register. Eventually I have checked the file `*.ulp.lst` and carefully compared instructions against ulp implementation. And in my opinion (and my ESP32 agree, because it seems to work this way), the unconditional jump to the address from the register is translated incorrectly. For example `jump r0` is translated to `00000080` which for me is clearly jump to immediate 0x0 so beginning of the program, the bit `sel` is not set. Every similar instruction `jump r1`, `jump r2`, jump r3` works the same way: `01000080`, `02000080`, `03000080`. The lower/upper case does not matter so `JUMP R0` is translated the same way that `jump r0` and so on.

**Comment by Mucka** [comment]
I checked source and found mistake that causes that bug, leaved solution in: #3

**Comment by krzychb** [comment]
Hey Mucka,
Fix merged in 3d299e3dc0cb2ea975aa128b9d90b49f84d0d2bf
Thank you for your time documenting the issue and preparing the MR!
It was already helpful to others in https://www.esp32.com/viewtopic.php?f=2&t=3228&p=15126&hilit=ulp+jump#p15129
 :+1:
