### ISSUE TITLE
Can't build .S files

### ISSUE THREAD

**Issue by No-0n3** [espressif/binutils-esp32ulp#6]
Testing out the ULP and now written a program in an .S file. But it doesn't get compiled. Have the latest download that you link in the wiki.  
  
**The errors**:  
> /home/user/esp/esp-idf/components/ulp/component_ulp_common.mk:28: warning: undefined variable 'ULP_LD_TEMPLATE'
> make[1]: *** No rule to make target 'hall_sensor.ulp.o', needed by 'ulp_main.elf'.  Stop.
> make: *** [C:/msys32/home/user/esp/esp-idf/make/project.mk:448: component-main-build] Error 2

Have followed the instructions on https://esp-idf.readthedocs.io/en/latest/api-guides/ulp.html  

**component.mk**:  
> \#
> \# Main component makefile.
> \#
> \# This Makefile can be left empty. By default, it will take the sources in the 
> \# src/ directory, compile them and link them into lib(subdirectory_name).a 
> \# in the build directory. This behaviour is entirely configurable,
> \# please read the ESP-IDF documents if you need to do this.
> \#
> 
> ULP_APP_NAME ?= ulp_$(COMPONENT_NAME)
> ULP_S_SOURCES = $(addprefix $(COMPONENT_PATH)/ulp/, hall_sensor.S)
> ULP_EXP_DEP_OBJECTS := main.o
> include $(IDF_PATH)/components/ulp/component_ulp_common.mk

Any help is appreciated.

**Comment by igrr** [comment]
It's quite odd that `ULP_LD_TEMPLATE` ends up being undefined. It is exported in components/ulp/Makefile.projbuild.

Can you try building one of the ULP examples in IDF first, like examples/system/ulp, and see if you get the same error?

**Comment by igrr** [comment]
Closing as no feedback, please feel free to reopen if the issue persists.
